name: 'telegram_pipeline'
version: '1.0.0'
config-version: 2

profile: 'telegram_pipeline'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  telegram_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table