telegram_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: ${DB_HOST}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      port: ${DB_PORT}
      dbname: ${DB_NAME}
      schema: staging
      threads: 4
      keepalives_idle: 0